-- =========================================================
-- AMBER & ASH — DATABASE SCHEMA
-- Run this once in Supabase: Dashboard -> SQL Editor -> New query
-- Paste this whole file, then click "Run".
-- =========================================================

-- ---------------------------------------------------------
-- 1. PROFILES
-- Supabase Auth already manages login/passwords in a private
-- "auth.users" table we don't touch directly. This "profiles"
-- table is OUR table that adds app-specific info (like role)
-- for each user, linked by the same id.
-- ---------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

-- Every time someone registers, auth.users gets a new row.
-- This trigger automatically creates a matching profiles row
-- for them, defaulting to the 'customer' role.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper function: checks if the CURRENTLY LOGGED IN user is an admin.
-- "security definer" lets it read profiles without getting tangled in
-- profiles' own security rules (avoids infinite recursion).
create function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- ---------------------------------------------------------
-- 2. PRODUCTS  (the coffee menu)
-- ---------------------------------------------------------
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  origin text not null,
  notes text not null,
  price numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------
-- 3. ORDERS + ORDER ITEMS
-- ---------------------------------------------------------
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'completed', 'cancelled')),
  total numeric(10, 2) not null,
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null, -- snapshot, in case the product changes later
  price numeric(10, 2) not null,
  qty int not null check (qty > 0)
);

-- =========================================================
-- ROW LEVEL SECURITY (RLS)
-- This is what actually enforces "customers can only see their
-- own orders" and "only admins can edit the menu" at the
-- database level — not just hidden in the frontend.
-- =========================================================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- PROFILES: you can see/update your own profile; admins can see all
create policy "view own profile" on public.profiles
  for select using (auth.uid() = id or public.is_admin());

create policy "update own profile" on public.profiles
  for update using (auth.uid() = id);

-- PRODUCTS: anyone can view the menu (even logged out); only admins can change it
create policy "anyone can view products" on public.products
  for select using (true);

create policy "admins manage products" on public.products
  for all using (public.is_admin()) with check (public.is_admin());

-- ORDERS: customers see/create only their own orders; admins see/update all
create policy "customers view own orders" on public.orders
  for select using (auth.uid() = user_id or public.is_admin());

create policy "customers create own orders" on public.orders
  for insert with check (auth.uid() = user_id);

create policy "admins update orders" on public.orders
  for update using (public.is_admin());

-- ORDER ITEMS: follow the same rule as their parent order
create policy "view own order items" on public.order_items
  for select using (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
      and (orders.user_id = auth.uid() or public.is_admin())
    )
  );

create policy "create own order items" on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders
      where orders.id = order_items.order_id
      and orders.user_id = auth.uid()
    )
  );

-- ---------------------------------------------------------
-- 4. SEED DATA — your existing menu, now living in the database
-- ---------------------------------------------------------
insert into public.products (name, origin, notes, price) values
 
  ('Caffè Latte', ' Espresso Roast', 'Rich espresso, steamed milk, smooth creamy finish', 3.50),
  ('Cappuccino', ' Espresso Roast', 'Bold espresso, steamed milk, thick foam', 3.25),
  ('Caffè Americano', ' Espresso Roast', 'Espresso with hot water, rich and smooth', 2.75),
  ('Espresso', ' Espresso Roast', 'Intense roasted coffee, rich crema', 2.25),
  ('Caramel Macchiato', ' Espresso Roast', 'Vanilla, steamed milk, espresso, caramel drizzle', 4.25),
  ('Caffè Mocha', ' Espresso Roast', 'Espresso, chocolate, steamed milk, whipped cream', 4.00),
  ('White Chocolate Mocha', ' Espresso Roast', 'Espresso, white chocolate, creamy milk', 4.25),
  ('Coffee Cold Brew', ' Cold Brew Blend', 'Smooth cold-steeped coffee with low bitterness', 3.50),
  ('Vanilla Sweet Cream Cold Brew', ' Cold Brew Blend', 'Cold brew with vanilla and sweet cream', 4.25),
  ('Nitro Cold Brew', ' Cold Brew Blend', 'Smooth nitrogen-infused cold brew', 4.50),
  ('Iced Caramel Macchiato', ' Espresso Roast', 'Iced milk, vanilla, espresso and caramel', 4.25),
  ('Iced Brown Sugar Oatmilk Shaken Espresso', ' Blonde Espresso', 'Brown sugar, espresso, oatmilk and cinnamon', 4.50),
  ('Iced Shaken Espresso', ' Blonde Espresso', 'Shaken espresso, ice and lightly sweetened flavor', 3.75),
  ('Iced Lavender Latte', ' Espresso Roast', 'Espresso, milk and delicate lavender flavor', 4.50),
  ('Iced Lavender Cream Chai', ' Premium Chai', 'Spiced chai with lavender cream cold foam', 4.75),
  ('Iced Ube Coconut Macchiato', ' Espresso Roast', 'Espresso, coconut, ube and creamy cold foam', 5.00),
  ('Toasted Coconut Cream Cold Brew', ' Cold Brew Blend', 'Cold brew with toasted coconut and creamy foam', 4.75),
  ('Toasted Coconut Latte', ' Espresso Roast', 'Espresso, milk and toasted coconut flavor', 4.50),
  ('Matcha Latte', 'Japanese-style Matcha', 'Smooth matcha with creamy milk', 4.00),
  ('Iced Matcha Latte', 'Japanese-style Matcha', 'Iced matcha with creamy milk', 4.25),
  ('Iced Lavender Cream Matcha', 'Japanese-style Matcha', 'Matcha with lavender cream cold foam', 4.75),
  ('Chai Latte', 'Premium Black Tea Chai', 'Black tea, cinnamon, cardamom, clove and ginger', 3.75),
  ('Strawberry Açaí Refresher', 'Strawberry & Açaí Blend', 'Sweet strawberry and tropical fruit flavors', 4.00),
  ('Mango Dragonfruit Refresher', 'Mango & Dragonfruit Blend', 'Tropical mango and dragonfruit flavors', 4.00),
  ('Pink Drink', 'Strawberry & Coconut Blend', 'Strawberry flavors with creamy coconutmilk', 4.50),
  ('Tropical Butterfly Refresher', 'Passionfruit & Guava Blend', 'Passionfruit, guava, mango-pineapple pearls and butterfly pea', 4.75),
  ('Blue Coconut Refresher', 'Coconut, Strawberry & Açaí Blend', 'Coconut, strawberry and açaí with vibrant blue color', 4.75),
  ('Smores Frappuccino', ' Coffee Blend', 'Coffee, vanilla, chocolate and marshmallow flavors', 5.25),
  ('Caramel Frappuccino', ' Coffee Blend', 'Blended coffee, caramel and creamy whipped topping', 4.75),
  ('Java Chip Frappuccino', ' Coffee Blend', 'Coffee, chocolate chips, mocha and creamy topping', 5.00);